// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz2sKUu0ANXasb-Ug60wJ--QdqI4sTfWM',
    appId: '1:105148674117:web:c05bca3f40a806bd1b332c',
    messagingSenderId: '105148674117',
    projectId: 'catch-pokemon-43b1f',
    authDomain: 'catch-pokemon-43b1f.firebaseapp.com',
    storageBucket: 'catch-pokemon-43b1f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKq7HUlmk5f5yr8IIcK42iFGT1jmSOPbI',
    appId: '1:105148674117:android:73f4483a6e19f1eb1b332c',
    messagingSenderId: '105148674117',
    projectId: 'catch-pokemon-43b1f',
    storageBucket: 'catch-pokemon-43b1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQrlKTeB3G79NhgzmWACTU-NjZrG2H4Yo',
    appId: '1:105148674117:ios:a5a50bd313f45c571b332c',
    messagingSenderId: '105148674117',
    projectId: 'catch-pokemon-43b1f',
    storageBucket: 'catch-pokemon-43b1f.appspot.com',
    iosBundleId: 'com.example.catchPokemonApp',
  );
}
